driver:
  name: rsync
  ssh_key: ~/.vagrant.d/insecure_private_key
  username: vagrant
  hostname: compkafkakit0101.softlayer.local
  privileged: true 
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: rsyn

provisioner:
  name: rsync

platforms:
- name: centos-7
  driver:
    image: rsync/centos-7
    pid_one_command: /usr/lib/systemd/systemd
- name: centos7-x86_84

suites:
  - name: default
    run_list:
    - recipe[krb5]
  - name: kadmin
    run_list:
    - recipe[krb5::kdc_init]
    - recipe[krb5::kadmin_init]
    - recipe[krb5::kadmin_service]
    - recipe[krb5::kdc_service]
    attributes:
      krb5:
        kadmin:
          service_actions: 'start'
        kdc:
          service_actions: 'start'
        krb5_conf:
          realms:
            default_realm_admin_server: 'compkafkait0101.softlayer.local'
  - name: rkerberos
    run_list:
    - recipe[krb5::rkerberos_gem]
  - name: keytab
    run_list:
    - recipe[krb5::kdc_init]
    - recipe[krb5::kdc_service]
    - recipe[krb5::kadmin_init]
    - recipe[krb5::kadmin_service]
    - recipe[krb5::host_keytab]
    attributes:
      krb5:
        kadmin:
          service_actions: 'start'
        kdc:
          service_actions: 'start'
        krb5_conf:
          realms:
            default_realm_admin_server: 'compkafkait0101.softlayer.local'
  - name: legacy
    run_list:
    - recipe[krb5]
    attributes:
      krb5:
        krb5_conf:
          realms:
            realms:
            - LOCAL
